# Generated by Django 4.2.5 on 2023-11-05 21:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('nombre_usuario', models.CharField(max_length=50)),
                ('tipo_socio', models.CharField(choices=[('SocioColab', 'Socio Colaborador'), ('Socio', 'Socio'), ('ADMIN', 'ADMIN')], default=('Socio', 'Socio'), max_length=15)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cancha',
            fields=[
                ('id_cancha', models.UUIDField(default=uuid.UUID('4b12d7cc-95ca-4e33-90b4-3ca983234aba'), primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=80)),
                ('habilitado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='HorarioBase',
            fields=[
                ('id_bloque', models.UUIDField(default=uuid.UUID('ba429fbc-0834-4a28-bce2-e38de7a6c376'), primary_key=True, serialize=False)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='HorarioCancha',
            fields=[
                ('id_horario', models.UUIDField(default=uuid.UUID('3c3dbb7c-fda1-4140-8739-867c0b044ff4'), primary_key=True, serialize=False)),
                ('fecha_horario', models.DateField()),
                ('disponibilidad', models.BooleanField(default=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('id_bloque', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.horariobase')),
                ('id_cancha', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.cancha')),
            ],
        ),
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id_imagen', models.UUIDField(default=uuid.UUID('e5fbbd6c-8f4e-4434-89a1-c039677a24d8'), primary_key=True, serialize=False)),
                ('imagen', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reserva', models.DateField()),
                ('horario_cancha', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.horariocancha')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_noticia', models.CharField(max_length=100)),
                ('sub_titulo', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('fecha_noticia', models.DateField()),
                ('cuerpo', models.TextField()),
                ('imagen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.imagen')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
