# Generated by Django 4.2.5 on 2023-11-05 21:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_cancha_id_cancha_alter_horariobase_id_bloque_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancha',
            name='id_cancha',
            field=models.UUIDField(default=uuid.UUID('295cf138-b368-47df-b0ce-4742292c1240'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='horariobase',
            name='id_bloque',
            field=models.UUIDField(default=uuid.UUID('0d55a2fd-38db-42f7-9a6b-56ad17ee994b'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='horariocancha',
            name='id_horario',
            field=models.UUIDField(default=uuid.UUID('2659563c-3e93-428f-aa18-4c8550144b8a'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='imagen',
            name='id_imagen',
            field=models.UUIDField(default=uuid.UUID('5925bd97-272b-4c81-83c7-68befc6c1d2e'), primary_key=True, serialize=False),
        ),
    ]
